apiVersion: v1
kind: Service
metadata:
  name: k8s-cicd-demo
  labels:
    app: k8s-cicd-demo
spec:
  type: NodePort
  selector:
    app: k8s-cicd-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080

